### ISSUE TITLE
Bring code up-to-date

### ISSUE THREAD

**Issue by rpadrela** [coherence/packet-replay-server#74]
Background

The repository hasn't been maintained for a while and we want to keep it up-to-date.

Expected

- Need to change reference on github.com/piot/brisk-protocol-go to github.com/coherence/brisk-protocol-go
- Need to change reference on github.com/piot/briskd-go to github.com/coherence/briskd-go
- The code in general needs to be brought up-to-date with latest versions of its dependencies

**Comment by Jan-Coherence** [comment]
Checked with Mathias, issue no longer valid.
